---
- name: Remove Cluster Docker Swarm
  hosts: docker_swarm
  become: true
  tasks:
    - name: Verifica se o Docker Swarm está habilitado
      shell: docker info
      changed_when: False
      register: docker_info
      become: yes
    
    - name: Remove nós do Docker Swarm
      shell: docker swarm leave --force
      become: yes
      
      